### ISSUE TITLE
repositoryId and categoryId are hard coding to create discussions.

### ISSUE THREAD

**Issue by m-hamashita** [rebase-network/hello-world#281]
Anyone can create a discussion in this repository using [this ID](https://github.com/rebase-network/who-is-hiring/blob/2ce87b7c53f71d2989413490e904a74a85530e19/.github/workflows/issue.yml#L52).
ex. https://github.com/rebase-network/hello-world/discussions/276, https://github.com/rebase-network/hello-world/discussions/277

I would appreciate it if you could remove these discussions :pray: (I have no authority to delete these discussions...)

**Comment by luckyyang** [comment]
Deleted
